export const SET_INITIAL_DATA = 'SET_INITIAL_DATA';
export const SHOW_WIDGET = 'SHOW_WIDGET';
export const ON_INIT = 'ON_INIT';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
