
export const PATIENT_TRACKING_FETCH_REQUESTED = 'PATIENT_TRACKING_FETCH_REQUESTED';
export const PATIENT_TRACKING_FETCH_SUCCEEDED = 'PATIENT_TRACKING_FETCH_SUCCEEDED';
export const PATIENT_TRACKING_FETCH_FAILED = 'PATIENT_TRACKING_FETCH_FAILED';

export const PATIENT_TRACKING_NEXT_PAGE = 'PATIENT_TRACKING_NEXT_PAGE';
export const SKIP_NEXT_PATIENT_TRACKING_DATA = 'SKIP_NEXT_PATIENT_TRACKING_DATA';

export const PATIENT_TRACKING_SORT_COLUMN = 'PATIENT_TRACKING_SORT_COLUMN';

export const REFRESH_PATIENT_TRACKING_DATA = 'REFRESH_PATIENT_TRACKING_DATA';
