export const ADVANCE_SEARCH_TOGGLE = 'ADVANCE_SEARCH_TOGGLE';

export const CLEAR_FIELDS = 'CLEAR';

export const SEARCH_INIT = 'SEARCH_INIT';
export const SEARCH_SUCCEEDED = 'SEARCH_SUCCEEDED';
export const SEARCH_FAILED = 'SEARCH_FAILED';

export const GET_NEXT_PATIENT_DATA = 'GET_NEXT_PATIENT_DATA';
export const SKIP_NEXT_PATIENT_DATA = 'SKIP_NEXT_PATIENT_DATA';
export const LAST_PAGE_ARRIVED = 'LAST_PAGE_ARRIVED';

export const DATE_VIEW_CHANGE = 'DATE_VIEW_CHANGE';

export const PATIENT_SELECTION = 'PATIENT_SELECTION';

export const APPOINTMENT_VIEW = 'APPOINTMENTS_VIEW';

export const LATEST_ENCOUNTER_DATE = 'LATEST_ENCOUNTER_DATE';
export const LATEST_ENCOUNTER_FETCH_SUCCEEDED = 'LATEST_ENCOUNTER_FETCH_SUCCEEDED';
export const LATEST_ENCOUNTER_FETCH_FAILED = 'LATEST_ENCOUNTER_FETCH_FAILED';

export const SORT_COLUMN = 'SORT_COLUMN';
