
export const DOCUMENT_TABS_FETCH_REQUESTED = 'DOCUMENT_TABS_FETCH_REQUESTED';
export const DOCUMENT_TABS_FETCH_SUCCEEDED = 'DOCUMENT_TABS_FETCH_SUCCEEDED';
export const DOCUMENT_TABS_FETCH_FAILED = 'DOCUMENT_TABS_FETCH_FAILED';

export const DOCUMENT_TABS_NEXT_PAGE = 'DOCUMENT_TABS_NEXT_PAGE';
export const SKIP_NEXT_DOCUMENT_TABS_DATA = 'SKIP_NEXT_DOCUMENT_TABS_DATA';

export const DOCUMENT_TABS_SORT_COLUMN = 'DOCUMENT_TABS_SORT_COLUMN';

export const DOCUMENT_TAB_SELECTION = 'DOCUMENT_TAB_SELECTION';

export const BACK_TO_DOCUMENT_TABS = 'BACK_TO_DOCUMENT_TABS';
