
export const NO_TASKGRID_FETCH_REQUESTED = 'NO_TASKGRID_FETCH_REQUESTED';
export const NO_TASKGRID_FETCH_SUCCEEDED = 'NO_TASKGRID_FETCH_SUCCEEDED';
export const NO_TASKGRID_FETCH_FAILED = 'NO_TASKGRID_FETCH_FAILED';

export const NO_TASKGRID_NEXT_PAGE = 'NO_TASKGRID_NEXT_PAGE';
export const SKIP_NEXT_NO_TASKGRID_DATA = 'SKIP_NEXT_NO_TASKGRID_DATA';
export const NO_TASKGRID_ROOM_UPDATE_REQUESTED = 'NO_TASKGRID_ROOM_UPDATE_REQUESTED';
export const NO_TASKGRID_ROOM_UPDATE_SUCCEEDED = 'NO_TASKGRID_ROOM_UPDATE_SUCCEEDED';
export const NO_TASKGRID_ROOM_UPDATE_FAILED = 'NO_TASKGRID_ROOM_UPDATE_FAILED';
export const NO_TASKGRID_GET_ROOM_LIST = 'NO_TASKGRID_GET_ROOM_LIST';
export const CHECKOUT_ON_NO_TASKGRID_DATA_REQUESTED = 'CHECKOUT_ON_NO_TASKGRID_DATA_REQUESTED';
export const CHECKOUT_ON_NO_TASKGRID_DATA_SUCCEEDED = 'CHECKOUT_ON_NO_TASKGRID_DATA_SUCCEEDED';
export const CHECKOUT_ON_NO_TASKGRID_DATA_FAILED = 'CHECKOUT_ON_NO_TASKGRID_DATA_FAILED';

