import { generateActionTypes } from '../../appointments/constants/ActionTypes';
import moduleName from './moduleName';

export const {
  APPOINTMENT_VIEW,
  APPOINTMENT_SELECTION,
  APPOINTMENT_FETCH_REQUESTED,
  APPOINTMENT_FETCH_SUCCEEDED,
  APPOINTMENT_FETCH_FAILED,
  APPOINTMENT_SORT_COLUMN,
  APPOINTMENT_SEARCH_VIEW,
  APPOINTMENT_SET_FILTER,
  APPOINTMENT_NEXT_PAGE,
  APPOINTMENT_FETCH_FILTER_REQUESTED,
  APPOINTMENT_CLEAR,
  SKIP_NEXT_APPOINTMENT_DATA,
} = generateActionTypes(moduleName);
