export const ITEMS_LOAD_SUCCESS = 'ITEMS_LOAD_SUCCESS';
export const ITEMS_LOAD_FAILED = 'ITEMS_LOAD_FAILED';

export const GET_USER_API = 'GET_USER_API';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const GET_PLANETS = 'GET_PLANETS';
export const PLANETS_LOAD_SUCCESS = 'PLANETS_LOAD_SUCCESS';
export const PLANETS_LOAD_FAILED = 'PLANETS_LOAD_FAILED';
