export const GET_PROVIDERS_SUCCEDED = 'GET_PROVIDERS_SUCCEDED';
export const GET_PROVIDERS_FAILED = 'GET_PROVIDERS_FAILED';

export const GET_LOCATIONS_SUCCEDED = 'GET_LOCATIONS_SUCCEDED';
export const GET_LOCATIONS_FAILED = 'GET_LOCATIONS_FAILED';

export const GET_ROOMS_SUCCEDED = 'GET_ROOMS_SUCCEDED';
export const GET_ROOMS_FAILED = 'GET_ROOMS_FAILED';

export const GET_PATIENT_STATUS_TYPES_SUCCEDED = 'GET_PATIENTSTATUSTYPES_SUCCEDED';
export const GET_PATIENT_STATUS_TYPES_FAILED = 'GET_PATIENTSTATUSTYPES_FAILED';

export const CHARTBINFILTER_TOGGLE_VISIBLITY = 'CHARTBINFILTER_TOGGLE_VISIBLITY';
export const CHARTBINFILTER_DEFAULT_SELECTED = 'CHARTBINFILTER_DEFAULT_SELECTED';

export const CHARTBINFILTER_APPOINTMENT_FILTER = 'CHARTBINFILTER_APPOINTMENT_FILTER';
export const CHARTBINFILTER_RESET_DEFAULT = 'CHARTBINFILTER_RESET_DEFAULT';
export const CHARTBINFILTER_DATECHANGE = 'CHARTBINFILTER_DATECHANGE';
export const CHARTBINFILTER_INITIAL_DATA_REQUESTED = 'CHARTBINFILTER_INITIAL_DATA_REQUESTED';
export const CHARTBINFILTER_RESET_GRID = 'CHARTBINFILTER_RESET_GRID';
export const CHARTBINFILTER_DATE_VALIDATE = 'CHARTBINFILTER_DATE_VALIDATE';

export const CHARTBINFILTER_SET_ROOM_VISIBILITY = 'CHARTBINFILTER_SET_ROOM_VISIBILITY';
