export const DISPLAY_TIMEOUTALERT = 'DISPLAY_TIMEOUTALERT';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const TIMEOUTALERT_SESSION_CONTINUE = 'TIMEOUTALERT_SESSION_CONTINUE';
export const TIMEOUTALERT_SESSION_SIGNOUT = 'TIMEOUTALERT_SESSION_SIGNOUT';
export const TIMEOUTALERT_SESSION_EXPIRED = 'TIMEOUTALERT_SESSION_EXPIRED';
export const TIMEOUTALERT_REMOTE_SESSION_EXPIRING = 'TIMEOUTALERT_REMOTE_SESSION_ENDING';
export const TIMEOUTALERT_UPDATE_COUNTDOWN_TIME = 'TIMEOUTALERT_UPDATE_COUNTDOWN_TIME';
