export const TASKINGDETAILS_LOAD_SUCCEDED = 'TASKINGDETAILS_LOAD_SUCCEDED';
export const TASKINGDETAILS_LOAD_FAILED = 'TASKINGDETAILS_LOAD_FAILED';

export const TASK_STATUS_START = 'TASK_STATUS_START';
export const TASK_STATUS_HOLD = 'TASK_STATUS_HOLD';
export const TASK_STATUS_UNHOLD = 'TASK_STATUS_UNHOLD';
export const TASK_STATUS_COMPLETE = 'TASK_STATUS_COMPLETE';
export const TASK_STATUS_CANCEL = 'TASK_STATUS_CANCEL';
export const TASK_GET_ROOM_LIST = 'TASK_GET_ROOM_LIST';
export const TASK_CHANGE_SEQUENCE = 'TASK_CHANGE_SEQUENCE';

export const TASK_STATUSUPDATE_SUCCEDED = 'TASK_STATUSUPDATE_SUCCEDED';
export const TASK_STATUSUPDATE_FAILED = 'TASK_STATUSUPDATE_FAILED';
export const TASK_CHANGE_SEQUENCE_SUCCEDED = 'TASK_CHANGE_SEQUENCE_SUCCEDED';
export const TASK_CHANGE_SEQUENCE_FAILED = 'TASK_CHANGE_SEQUENCE_FAILED';

export const FILTERS_TOGGLE_VISIBLITY = 'FILTERS_TOGGLE_VISIBLITY';

export const NESTEDTASK_TOGGLE_VISIBLITY = 'NESTEDTASK_TOGGLE_VISIBLITY';

export const NOTASKGRID_TOGGLE_VISIBLITY = 'NOTASKGRID_TOGGLE_VISIBLITY';

export const PATIENTS_LOAD = 'PATIENTS_LOAD';
export const PATIENT_TOGGLE_SELECTED = 'PATIENT_TOGGLE_SELECTED';

export const TASK_SAVE_REQUESTED = 'TASK_SAVE_REQUESTED';
export const TASK_SAVE_FAILED = 'TASK_SAVE_FAILED';
export const TASK_SAVE_SUCCESS = 'TASK_SAVE_SUCCESS';
export const TASK_START_POLLING = 'TASK_START_POLLING';
export const TASK_STOP_POLLING = 'TASK_STOP_POLLING';
export const TASK_REFRESH_COUNTER_TICK = 'TASK_REFRESH_COUNTER_TICK';
export const TASK_FETCH_TASKS_FOR_ENCOUNTER = 'TASK_FETCH_TASKS_FOR_ENCOUNTER_REQUESTED';
export const TASK_FETCH_TASKS_FOR_ENCOUNTER_COMPLETED = 'TASK_FETCH_TASKS_FOR_ENCOUNTER_COMPLETED';
export const TASK_FETCH_TASKS_FOR_ENCOUNTER_FAILED = 'TASK_FETCH_TASKS_FOR_ENCOUNTER_FAILED';
export const REFRESH_TASKING_DATA = 'REFRESH_TASKING_DATA';
export const GET_FAVORITE_LIST = 'GET_FAVORITE_LIST';
export const TASK_FAVORITE_SUCCESS = 'TASK_FAVORITE_SUCCESS';
export const TASK_FAVORITE_FAILED = 'TASK_FAVORITE_FAILED';
export const TASK_ALERT_CLICK = 'TASK_ALERT_CLICK';
export const TASK_FAVORITE_TEMPLATE_DELETE = 'TASK_FAVORITE_TEMPLATE_DELETE';
export const TASK_FAVORITE_TEMPLATE_CREATE = 'TASK_FAVORITE_TEMPLATE_CREATE';
