export const GET_DRAWERS_SUCCEDED = 'GET_DRAWERS_SUCCEDED';
export const GET_DRAWERS_FAILED = 'GET_DRAWERS_FAILED';

export const DOCUMENTTABS_FILTER_TOGGLE_VISIBLITY = 'DOCUMENTTABS_FILTER_TOGGLE_VISIBLITY';

export const FILTER_DOCUMENT_TABS = 'FILTER_DOCUMENT_TABS';
export const DOCUMENTTABS_FILTER_RESET_DEFAULT = 'DOCUMENTTABS_FILTER_RESET_DEFAULT';
export const DOCUMENTTABS_FILTER_INITIAL_DATA_REQUESTED = 'DOCUMENTTABS_FILTER_INITIAL_DATA_REQUESTED';
export const RESET_DOCUMENTTABS_GRID = 'RESET_DOCUMENTTABS_GRID';
