export const TASKINGFORM_TOGGLE_VISIBLITY = 'TASKINGFORM_TOGGLE_VISIBLITY';
export const TASKINGFORM_RESIZEMODAL = 'TASKINGFORM_RESIZEMODAL';
export const TASKINGFORM_RESETTODEFAULT = 'TASKINGFORM_RESETTODEFAULT';
