export const SELECTED_CHART_CLEAR = 'SELECTED_CHART_CLEAR';
export const SELECTED_CHART_SET_PREV_ROUTE = 'SELECTED_CHART_SET_PREV_ROUTE';
export const SELECTED_CHART_SELECTED = 'SELECTED_CHART_SELECTED';
export const SELECTED_CHART_ENCOUNTER_SELECTED = 'SELECTED_CHART_ENCOUNTER_SELECTED';
export const SELECTED_CHART_SET_CHART = 'SELECTED_CHART_SET_CHART';
export const SELECTED_CHART_SET_ENCOUNTER = 'SELECTED_CHART_SET_ENCOUNTER';
