export const SET_INITIAL_DATA = 'SET_INITIAL_DATA';
export const SHOW_WIDGET = 'SHOW_WIDGET';
export const ON_INIT = 'ON_INIT';
export const WIDGET_OPENED = 'WIDGET_OPENED';
export const MEDICATION_CHANGED = 'MEDICATION_CHANGED';
export const MEDICATION_ADD_SUCCESS = 'MEDICATION_ADD_SUCCESS';
export const MEDICATION_ADD_FAILURE = 'MEDICATION_ADD_FAILURE';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const SCRIPT_LOAD_FAILED = 'SCRIPT_LOAD_FAILED';
export const SET_PATIENT_CONTEXT = 'SET_PATIENT_CONTEXT';
export const AUTHENTICATION_INITIATED = 'AUTHENTICATION_INITIATED';

export const ADD_LITENERS = 'ADD_LITENERS';
export const WIDGET_DATA_ADDED = 'WIDGET_DATA_ADDED';
export const WIDGET_DATA_ADDED_SUCCESSFULLY = 'WIDGET_DATA_ADDED_SUCCESSFULLY';
export const WIDGET_DATA_ADDED_FAILED = 'WIDGET_DATA_ADDED_FAILED';

export const PHARMACY_WIDGET_DATA_UPDATED = 'PHARMACY_WIDGET_DATA_UPDATED';
export const RX_WIDGETS_DETAILS_GET = 'RX_WIDGETS_DETAILS_GET';
export const RX_WIDGETS_DETAILS_GET_SUCCESSFULLY = 'RX_WIDGETS_DETAILS_GET_SUCCESSFULLY';

export const RX_WIDGETS_GET_SETTINGS = 'RX_WIDGETS_GET_SETTINGS';
export const RX_WIDGETS_GET_SETTINGS_SUCCESSFULLY = 'RX_WIDGETS_GET_SETTINGS_SUCCESSFULLY';
export const RX_WIDGETS_GET_SETTINGS_FAILED = 'RX_WIDGETS_GET_SETTINGS_FAILED';

export const NO_REQUEST = 'NO_REQUEST';
export const WIDGET_STATUS_PENDING = 'PENDING';
export const WIDGET_STATUS_SUCCESS = 'SUCCESS';
export const WIDGET_STATUS_FAILED = 'FAILED';
export const CHANGE_WIDGET = 'CHANGE_WIDGET';

export const CONSENT_SET_TRUE = 'CONSENT_SET_TRUE';
export const CONSENT_SET_FALSE = 'CONSENT_SET_FALSE';
export const CONSENT_NOT_SET = 'CONSENT_NOT_SET';

export const ADD_PRESCRIPTION_DATA = 'ADD_PRESCRIPTION_DATA';
export const MAP_COMPLETE_PRESCRIPTION_DATA = 'MAP_COMPLETE_PRESCRIPTION_DATA';
export const UPDATE_PRESCRIPTION_COMPLETE_STATUS = 'UPDATE_PRESCRIPTION_COMPLETE_STATUS';
export const UPDATE_PRESCRIPTION_FAILED = 'UPDATE_PRESCRIPTION_FAILED';

export const PRESCRIPTION_SEND = 'SEND';
export const PRESCRIPTION_SEND_PRINT = 'SEND_PRINT';
export const PRESCRIPTION_PRINT_NOT_SEND = 'PRINT_NOT_SEND';
export const PRESCRIPTION_SIGN_NOT_SEND = 'SIGN_NOT_SEND';
export const PRESCRIPTION_PENDING = 'PRESCRIPTION_PENDING';
export const PRESCRIPTION_UNDELIVERED = 'UNDELIVERED';

export const LOAD_SCRIPTS = 'LOAD_SCRIPTS';
export const PRESCRIPTION_CANCELLED = 'CANCELLED';
