export const ALLERGY_INTEGRATION_GROUP_ID = 14;
export const RX_INTEGRATION_GROUP_ID = 15;

export const DRUG_INTEGRATION_ENTITY_ID = 12;
export const ALLERGY_INTEGRATION_ENTITY_ID = 13;
export const ALLERGYGROUP_INTEGRATION_ENTITY_ID = 14;
export const MEDICATION_INTEGRATION_ENTITY_ID = 15;
export const PHARMACY_INTEGRATION_ENTITY_ID = 16;
export const PRESCRIPTION_INTEGRATION_ENTITY_ID = 17;

export const SOURCE_ID = 2;
