export const EMPLOYEE_SUCCESS = 'EMPLOYEE_SUCCESS';
export const EMPLOYEE_FAILED = 'EMPLOYEE_FAILED';

export const ON_EMP_CREATION = 'ON_EMP_CREATION';
export const ON_EMP_DELETION = 'ON_EMP_DELETION';
