
export const DOCUMENTS_FETCH_REQUESTED = 'DOCUMENTS_FETCH_REQUESTED';
export const DOCUMENTS_FETCH_SUCCEEDED = 'DOCUMENTS_FETCH_SUCCEEDED';
export const DOCUMENTS_FETCH_FAILED = 'DOCUMENTS_FETCH_FAILED';

export const DOCUMENTS_NEXT_PAGE = 'DOCUMENTS_NEXT_PAGE';
export const SKIP_NEXT_DOCUMENTS_DATA = 'SKIP_NEXT_DOCUMENTS_DATA';

export const DOCUMENTS_SORT_COLUMN = 'DOCUMENTS_SORT_COLUMN';

export const DOCUMENTCONTENT_FETCH_REQUESTED = 'DOCUMENTCONTENT_FETCH_REQUESTED';
export const DOCUMENTCONTENT_FETCH_SUCCEEDED = 'DOCUMENTCONTENT_FETCH_SUCCEEDED';
export const DOCUMENTCONTENT_FETCH_FAILED = 'DOCUMENTCONTENT_FETCH_FAILED';

export const PDF_NEXT_PAGE = 'PDF_NEXT_PAGE';
export const PDF_PREVIOUS_PAGE = 'PDF_PREVIOUS_PAGE';
export const PDF_ZOOM_IN = 'PDF_ZOOM_IN';
export const PDF_ZOOM_OUT = 'PDF_ZOOM_OUT';
export const PDF_DOCUMENT_LOADED = 'PDF_DOCUMENT_LOADED';
export const PDF_ROTATE_LEFT = 'PDF_ROTATE_LEFT';
export const PDF_ROTATE_RIGHT = 'PDF_ROTATE_RIGHT';

export const DOCUMENT_NOTES_VIEW = 'DOCUMENT_NOTES_VIEW';
export const DOCUMENT_NOTES_FETCH_SUCCEEDED = 'DOCUMENT_NOTES_FETCH_SUCCEEDED';
export const DOCUMENT_NOTES_FETCH_FAILED = 'DOCUMENT_NOTES_FETCH_FAILED';
export const DOCUMENT_NOTES_SORT_COLUMN = 'DOCUMENT_NOTES_SORT_COLUMN';
