export const DOCUMENT_FILTER_TOGGLE_VISIBLITY = 'DOCUMENT_FILTER_TOGGLE_VISIBLITY';
export const FILTER_DOCUMENT_LIST = 'FILTER_DOCUMENT_LIST';

export const DOCUMENT_FILTER_RESET_DEFAULT = 'DOCUMENT_FILTER_RESET_DEFAULT';
export const RESET_DOCUMENT_LIST = 'RESET_DOCUMENT_LIST';
