export const PATIENTALERT_TEXT_CHANGED = 'PATIENTALERT_TEXT_CHANGED';

export const PATIENTALERT_READ = 'PATIENTALERT_READ';
export const PATIENTALERT_READ_SUCCEDED = 'PATIENTALERT_READ_SUCCEDED';
export const PATIENTALERT_READ_FAILED = 'PATIENTALERT_READ_FAILED';

export const PATIENTALERT_SAVEUPDATE = 'PATIENTALERT_SAVEUPDATE';
export const PATIENTALERT_SAVEUPDATE_SUCCEDED = 'PATIENTALERT_SAVEUPDATE_SUCCEDED';
export const PATIENTALERT_SAVEUPDATE_FAILED = 'PATIENTALERT_SAVEUPDATE_FAILED';

export const PATIENTALERT_DELETE = 'PATIENTALERT_DELETE';
export const PATIENTALERT_DELETE_SUCCEDED = 'PATIENTALERT_DELETE_SUCCEDED';
export const PATIENTALERT_DELETE_FAILED = 'PATIENTALERT_DELETE_FAILED';

export const PATIENTALERT_TOGGLE_VISIBLITY = 'PATIENTALERT_TOGGLE_VISIBLITY';
export const PATIENTALERT_TOGGLE_EDITMODE = 'PATIENTALERT_TOGGLE_EDITMODE';
export const PATIENTALERT_RESETTODEFAULT = 'PATIENTALERT_RESETTODEFAULT';

export const PATIENTALERT_RESIZEMODAL = 'PATIENTALERT_RESIZEMODAL';
