export const APP_REGISTRATION_REGISTERED = 'APP_REGISTRATION_REGISTERED';
export const APP_REGISTRATION_UNREGISTERED = 'APP_REGISTRATION_UNREGISTERED';
export const APP_REGISTRATION_ENDPOINT_SELECTED = 'APP_REGISTRATION_ENDPOINT_SELECTED';
export const APP_REGISTRATION_ENDPOINT_UNSELECTED = 'APP_REGISTRATION_ENDPOINT_UNSELECTED';

