export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';
export const LOCATION_CHANGE_FULLSCREEN = '@@srs/LOCATION_CHANGE';
export const LOCATION_SET_FULL_SCREEN_MODE = 'LOCATION_SET_FULL_SCREEN_MODE';
